version: '2.4'
services:
    api:
        build:
            context: .
        ports: 
            - 3000:3000
        volumes:
            - .:/app/api:delegated
    stat-service:
        build:
            context: ../stat-service
        command: /start-reload.sh
        ports:
            - 3111:3111
        volumes:
            - ../stat-service:/app/stat-service:delegated
    frontend:
        build:
            context: ../frontend
        # command: "npm run serve"
        ports: 
            - 3333:8080
        volumes:
            - ../frontend:/app/frontend:delegated
            - /app/frontend/node_modules
        environment:
            - npm_config_unsafe_perm=true